const languages = {
   pt:{
      header_item1: 'Conheça a Sportify',
      header_item2: 'Pra quem é?',
      banner: 'Sua jornada começa aqui',
      banner_button: 'Cadastre-se',
      discover_title: 'Conheça a Sportify',
      discover_text: 'A Sportify é uma rede social dedicada à musculação e esportes, criada para conectar entusiastas de todas as idades e níveis de experiência. Nossa plataforma oferece um espaço acolhedor onde os usuários podem compartilhar treinos, trocar dicas, acompanhar seu progresso e encontrar motivação em uma comunidade vibrante e inspiradora. Seja você um iniciante ou um atleta experiente, a Sportify é o lugar perfeito para alcançar seus objetivos de forma saudável e eficiente.',
      mission_title: 'Missão',
      mission_text: 'Promover um ambiente inclusivo e motivador para entusiastas de musculação e esportes, facilitando a troca de conhecimentos e experiências que impulsionam o crescimento pessoal e físico de nossos usuários.',
      vision_title: 'Visão',
      vision_text: 'Ser a principal rede social para amantes de musculação e esportes, reconhecida por sua comunidade engajada e pelas ferramentas inovadoras que ajudam os usuários a atingir seus objetivos e melhorar sua qualidade de vida.',
      values_title: 'Valores',
      values_text1: 'Inclusão: Valorizamos a diversidade e acolhemos todos os indivíduos, independentemente de seu nível de experiência.',
      values_text2: 'Colaboração: Acreditamos na força da comunidade e incentivamos a troca de conhecimento e apoio mútuo.',
      values_text3: 'Saúde: Promovemos um estilo de vida saudável, priorizando o bem-estar físico e mental de nossos usuários.',
      who_is: 'Pra quem é a Sportify?',
      who_is_text: ` A Sportify é uma rede social para todos que amam musculação e esportes, desde iniciantes até atletas avançados. É um espaço para compartilhar treinos, acompanhar progressos e se conectar com pessoas com interesses semelhantes.
                     <br>
                     Além disso, a plataforma beneficia treinadores e profissionais, permitindo a expansão de redes de contatos e a oferta de orientações personalizadas. Com uma comunidade de apoio, a Sportify ajuda todos a alcançar seus objetivos de forma saudável.`,
      graph_title: 'Gráfico',
      graph1_label: '% da População frequentando academias',
      graph2_label: 'Quantidade de academias abertas',
      footer: 'Todos direitos reservados para Sportify<sup>©</sup> - 2024',
      aside_item1: 'Feed',
      aside_item2: 'Perfil',
      aside_item3: 'Dashboard',
      aside_item4: 'Receitas',
      aside_item5: 'Músicas',
      aside_item6: 'Jogos',
      dashboard_s1_kpi1: 'Última interação',
      dashboard_s1_kpi2: 'Total inerações',
      dashboard_s1_kpi3: 'Tipo mais usado',
      dashboard_s2_kpi1: 'Pontuação Total',
      dashboard_s2_kpi2: 'Pontuação Máxima',
      dashboard_s2_kpi3: 'Pontuação Média',
      dashboard_s2_kpi4: 'Tentativas',
      dashboard_s2_kpi5: 'Última Tentativa',
      change_section: 'Alternar Dashboard',
      add_post_button: 'Adicionar post',
      profile_recipes: 'Suas receitas',
      profile_posts: 'Seus posts',
      select_songs: 'Selecione seus estilos desejados:',
      selected_songs: 'Gêneros selecionados:',
      generated_songs: 'Playlist recomendada',
      genre_1: '🎮 Eletrônica',
      genre_2: '🎻 Sertanejo',
      genre_3: '🎰 Trap',
      genre_4: '🕶 Funk',
      genre_5: '🥁 Pagode/Samba',
      genre_6: '🎤 Rap',
      genre_7: '🎵 Pop',
      generate_playlist: 'Gerar Playlist'
   },
   en: {
      header_item1: 'Discover Sportify',
      header_item2: 'Who is it for?',
      banner: 'Your journey begins here',
      banner_button: 'Sign up',
      discover_title: 'Discover Sportify',
      discover_text: `Sportify is a social network dedicated to bodybuilding and sports, created to connect enthusiasts of all ages and experience levels. Our platform provides a welcoming space where users can share workouts, exchange tips, track their progress and find motivation in a vibrant and inspiring community. Whether you're a beginner or an experienced athlete, Sportify is the perfect place to reach your goals in a healthy and efficient way.`,
      mission_title: 'Mission',
      mission_text: 'Promote an inclusive and motivating environment for bodybuilding and sports enthusiasts, facilitating the exchange of knowledge and experiences that boost the personal and physical growth of our users.',
      vision_title: 'Vision',
      vision_text: `To be the main social network for bodybuilding and sports lovers, recognized for its engaged community and innovative tools that help users achieve their goals and improve their quality of life.`,
      values_title: 'Values',
      values_text1: 'Inclusion: We value diversity and welcome all individuals, regardless of their level of experience.',
      values_text2: 'Collaboration: We believe in the strength of the community and encourage knowledge sharing and mutual support.',
      values_text3: 'Health: We promote a healthy lifestyle, prioritizing the physical and mental well-being of our users.',
      who_is: 'Who is it for?',
      who_is_text: `Sportify is a social network for everyone who loves bodybuilding and sports, from beginners to advanced athletes. It’s a space to share workouts, track progress, and connect with people with similar interests.  
                    <br>  
                    Additionally, the platform benefits trainers and professionals, enabling them to expand their networks and offer personalized guidance. With a supportive community, Sportify helps everyone achieve their goals in a healthy way.`,
      graph_title: 'Graphics',
      graph1_label: '% of the Population Attending Gyms',
      graph2_label: 'Number of Gyms Opened',
      footer: 'All rights reserved to Sportify<sup>©</sup> - 2024',
      aside_item1: 'Feed',
      aside_item2: 'Profile',
      aside_item3: 'Dashboard',
      aside_item4: 'Recipes',
      aside_item5: 'Songs',
      aside_item6: 'Games',
      dashboard_s1_kpi1: 'Last interaction',
      dashboard_s1_kpi2: 'Total interactions',
      dashboard_s1_kpi3: 'Most used type',
      dashboard_s2_kpi1: 'Total Score',
      dashboard_s2_kpi2: 'Maximum Score',
      dashboard_s2_kpi3: 'Average Score',
      dashboard_s2_kpi4: 'Attempts',
      dashboard_s2_kpi5: 'Last Attempt',
      change_section: 'Switch Dashboard',
      add_post_button: 'Add post',
      profile_recipes: 'Your recipes',
      profile_posts: 'Your posts',
      select_songs: 'Select your desired styles:',
      selected_songs: 'Selected genres:',
      generated_songs: 'Playlist recommended',
      genre_1: '🎮 Electronic',
      genre_2: '🎻 Country',
      genre_3: '🎰 Trap',
      genre_4: '🕶 Funk',
      genre_5: '🥁 Pagode/Samba',
      genre_6: '🎤 Rap',
      genre_7: '🎵 Pop',
      generate_playlist: 'Generate Playlist'
   },
   es: {
      header_item1: 'Descubre Sportify',
      header_item2: '¿Para quién es?',
      banner: 'Tu viaje comienza aquí',
      banner_button: 'Regístrate',
      discover_title: 'Descubre Sportify',
      discover_text: `Sportify es una red social dedicada al culturismo y los deportes, creada para conectar a entusiastas de todas las edades y niveles de experiencia. Nuestra plataforma ofrece un espacio acogedor donde los usuarios pueden compartir entrenamientos, intercambiar consejos, seguir su progreso y encontrar motivación en una comunidad vibrante e inspiradora. Ya seas principiante o un atleta experimentado, Sportify es el lugar perfecto para alcanzar tus metas de manera saludable y eficiente.`,
      mission_title: 'Misión',
      mission_text: 'Promover un ambiente inclusivo y motivador para los entusiastas del culturismo y los deportes, facilitando el intercambio de conocimientos y experiencias que impulsen el crecimiento personal y físico de nuestros usuarios.',
      vision_title: 'Visión',
      vision_text: `Ser la principal red social para los amantes del culturismo y los deportes, reconocida por su comunidad comprometida y herramientas innovadoras que ayudan a los usuarios a alcanzar sus objetivos y mejorar su calidad de vida.`,
      values_title: 'Valores',
      values_text1: 'Inclusión: Valoramos la diversidad y damos la bienvenida a todas las personas, sin importar su nivel de experiencia.',
      values_text2: 'Colaboración: Creemos en la fuerza de la comunidad y fomentamos el intercambio de conocimientos y el apoyo mutuo.',
      values_text3: 'Salud: Promovemos un estilo de vida saludable, priorizando el bienestar físico y mental de nuestros usuarios.',
      who_is: '¿Para quién es?',
      who_is_text: `Sportify es una red social para todos los amantes del culturismo y los deportes, desde principiantes hasta atletas avanzados. Es un espacio para compartir entrenamientos, seguir el progreso y conectar con personas con intereses similares.  
                      <br>  
                      Además, la plataforma beneficia a entrenadores y profesionales, permitiéndoles ampliar sus redes y ofrecer orientación personalizada. Con una comunidad solidaria, Sportify ayuda a todos a alcanzar sus metas de manera saludable.`,
      graph_title: 'Gráficos',
      graph1_label: '% de la Población que Asiste a Gimnasios',
      graph2_label: 'Número de Gimnasios Abiertos',
      footer: 'Todos los derechos reservados a Sportify<sup>©</sup> - 2024',
      aside_item1: 'Feed',
      aside_item2: 'Perfil',
      aside_item3: 'Dashboard',
      aside_item4: 'Receta',
      aside_item5: 'Canciones',
      aside_item6: 'Juegos',
      dashboard_s1_kpi1: 'Última interacción',
      dashboard_s1_kpi2: 'Total interacciones',
      dashboard_s1_kpi3: 'Tipo más usado',
      dashboard_s2_kpi1: 'Puntuación Total',
      dashboard_s2_kpi2: 'Puntuación Máxima',
      dashboard_s2_kpi3: 'Puntuación Promedio',
      dashboard_s2_kpi4: 'Intentos',
      dashboard_s2_kpi5: 'Último Intento',
      change_section: 'Cambiar Dashboard',
      add_post_button: 'Agregar post',
      profile_recipes: 'Sus recetas',
      profile_posts: 'Sus posts',
      select_songs: 'Seleccione sus estilos deseados:',
      selected_songs: 'Géneros seleccionados:',
      generated_songs: 'Playlist recomendada',
      genre_1: '🎮 Electrónica',
      genre_2: '🎻 Música Sertaneja',
      genre_3: '🎰 Trap',
      genre_4: '🕶 Funk',
      genre_5: '🥁 Pagode/Samba',
      genre_6: '🎤 Rap',
      genre_7: '🎵 Pop',
      generate_playlist: 'Generar Playlist'
  }
  
}